

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mainpage;




import admin.Dashboard;
import config.config;
import user.Feed;
import admin.users;
import config.UserSession;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;


/**
 *
 * @author LAGARBE
 */
public class loginform extends javax.swing.JFrame {

    /**
     * Creates new form landpage
     */
    public loginform() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        em = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        ps = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Password :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(360, 330, 70, 30);

        em.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel1.add(em);
        em.setBounds(430, 280, 210, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Email :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(360, 280, 70, 30);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel16);
        jLabel16.setBounds(140, 50, 140, 140);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel19);
        jLabel19.setBounds(140, 50, 140, 140);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/S1M SPORTS CARS (2)-Picsart-BackgroundRemover (1)-Picsart-BackgroundRemover.jpg"))); // NOI18N
        jLabel8.setText("GOOD DAY!");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(750, 20, 260, 90);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Login Your Account");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(430, 240, 210, 30);
        jPanel1.add(ps);
        ps.setBounds(430, 330, 210, 30);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("LOGIN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(430, 370, 210, 23);

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Dont have an acc? Register here...");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(430, 400, 210, 23);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("GOOD DAY!");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(130, 20, 140, 140);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Untitled design (5).jpg"))); // NOI18N
        jLabel6.setText("GOOD DAY!");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(0, -30, 1010, 720);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1010, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 692, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1026, 731));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         // Get input values
    config con = new config();
    
    String email = em.getText().trim();
    String password = ps.getText().trim();
    
    // VALIDATION
    if (email.isEmpty() || password.isEmpty()) {
        JOptionPane.showMessageDialog(this,
            "Please enter Email and Password!",
            "Login Error",
            JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    if (!email.contains("@") || !email.contains(".")) {
        JOptionPane.showMessageDialog(this,
            "Wrong format Email!\nNeed '@' and '.'",
            "Email Format Error",
            JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    try {
        Connection conn = con.connectDB();
        
        // ✅ SELECT ALL USER INFO including us_id
       String sql = "SELECT us_id, username, email, role, status, profile_picture FROM tbl_user  WHERE email = ? AND pass = ?";
        PreparedStatement pstmt = conn.prepareStatement(sql);
        
        pstmt.setString(1, email);
        pstmt.setString(2, password);
        
        ResultSet rs = pstmt.executeQuery();
        
        if (rs.next()) {
            int userId = rs.getInt("us_id");
            String username = rs.getString("username");
            String userEmail = rs.getString("email");
            String role = rs.getString("role");
            String status = rs.getString("status");
            
            // CHECK STATUS
            if (status.equalsIgnoreCase("Pending")) {
                JOptionPane.showMessageDialog(this,
                    "Your account is pending approval.\nPlease wait for admin.",
                    "Account Pending",
                    JOptionPane.WARNING_MESSAGE);
                return;
                
            } else if (status.equalsIgnoreCase("Declined")) {
                JOptionPane.showMessageDialog(this,
                    "Your account has been declined.",
                    "Account Declined",
                    JOptionPane.ERROR_MESSAGE);
                return;
                
            } else if (status.equalsIgnoreCase("Approved")) {
                
                // ✅ SAVE USER DATA TO SINGLETON
                UserSession session = UserSession.getInstance();
               String profilePicture = rs.getString("profile_picture");
               session.setUserData(userId, username, userEmail, role, status, profilePicture);
                
                // CLOSE LOGIN WINDOW
                this.dispose();
                
                // REDIRECT BASED ON ROLE
                if (role.equalsIgnoreCase("admin")) {
                    JOptionPane.showMessageDialog(null, "Welcome Admin!");
                    Dashboard ad = new Dashboard();
                    ad.setVisible(true);
                    
                } else if (role.equalsIgnoreCase("user")) {
                    JOptionPane.showMessageDialog(null, "Welcome " + username + "!");
                    Feed ud = new Feed();
                    ud.setVisible(true);
                    
                } else {
                    JOptionPane.showMessageDialog(null, "Welcome!");
                    Feed ud = new Feed();
                    ud.setVisible(true);
                }
            }
            
        } else {
            JOptionPane.showMessageDialog(this,
                "Invalid Email or Password!",
                "Login Failed",
                JOptionPane.ERROR_MESSAGE);
        }
        
        rs.close();
        pstmt.close();
        conn.close();
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
            "Error: " + e.getMessage(),
            "Login Error",
            JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
        }
    }                                        

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {                                      
          String email = em.getText().trim();      // Email field
        String password = ps.getText().trim();   // Password field
        
        
        if (email.isEmpty() && password.isEmpty()) {
            
            JOptionPane.showMessageDialog(this, 
                "Plss, Enter your Password!", 
                "Login Error", 
                JOptionPane.ERROR_MESSAGE);
            return; 
            
        } else if (email.isEmpty()) {
            
            JOptionPane.showMessageDialog(this, 
                "Tinapolan ay, Butangi Email!", 
                "Login Error", 
                JOptionPane.ERROR_MESSAGE);
            return;
            
        } else if (password.isEmpty()) {
            
            JOptionPane.showMessageDialog(this, 
                "walay password, Bading!", 
                "Login Error", 
                JOptionPane.ERROR_MESSAGE);
            return;
            
        } else {
            
            if (!email.contains("@") || !email.contains(".")) {
                JOptionPane.showMessageDialog(this, 
                    "Wrong format Email!\need '@' and '.'", 
                    "Email Format Error", 
                    JOptionPane.ERROR_MESSAGE);
                return;
            }
            
        
       this.dispose();  
       Feed log = new Feed();
       log.setVisible(true);
        }
    }                                     

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {                                      
        this.dispose();
        registerpage register = new registerpage();
        register.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        registerpage register = new registerpage();
        register.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField em;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField ps;
    // End of variables declaration//GEN-END:variables

    private static class admindashboard {

        public admindashboard() {
        }

        private void setVisible(boolean b) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }
    }

    private static class registerform {

        public registerform() {
        }

        private void setVisible(boolean b) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }
    }
}
