/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mainpage;

import config.config;
import mainpage.landpage;
import javax.swing.JOptionPane;
/**
 *
 * @author LAGARBE
 */
public class registerpage extends javax.swing.JFrame {

    /**
     * Creates new form registerpage
     */
    public registerpage() {
      initComponents();
    createAdminIfNotExists(); // ← ADD THIS LINE
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        jPanel1 = new javax.swing.JPanel();
        name = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        uemail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        pass = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(null);

        name.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        jPanel1.add(name);
        name.setBounds(440, 280, 210, 30);
        jPanel1.add(jLabel5);
        jLabel5.setBounds(350, 30, 0, 40);

        uemail.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        uemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uemailActionPerformed(evt);
            }
        });
        jPanel1.add(uemail);
        uemail.setBounds(440, 330, 210, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("User email :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(360, 330, 80, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Password :");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(360, 380, 80, 30);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("REGISTERED");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(440, 420, 210, 23);

        jLabel17.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Plss Register here.");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(340, 200, 400, 50);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/S1M SPORTS CARS (2)-Picsart-BackgroundRemover (1)-Picsart-BackgroundRemover.jpg"))); // NOI18N
        jLabel13.setText("GOOD DAY!");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(780, 10, 250, 80);

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Return...");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(440, 450, 210, 20);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("User name :");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(360, 280, 80, 30);
        jPanel1.add(pass);
        pass.setBounds(440, 380, 210, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Untitled design (5).jpg"))); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(0, 0, 1020, 690);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1020, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 691, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

       String username = name.getText().trim();
    String email = uemail.getText().trim();
    String password = pass.getText().trim();
    
    // VALIDATION (check first before inserting)
    if (username.isEmpty() && email.isEmpty() && password.isEmpty()) {
        JOptionPane.showMessageDialog(this,
            "Please fill up all fields!",
            "Registration Error",
            JOptionPane.ERROR_MESSAGE);
        return;
    } else if (username.isEmpty()) {
        JOptionPane.showMessageDialog(this,
            "Please enter Username!",
            "Registration Error",
            JOptionPane.ERROR_MESSAGE);
        return;
    } else if (email.isEmpty()) {
        JOptionPane.showMessageDialog(this,
            "Please enter Email!",
            "Registration Error",
            JOptionPane.ERROR_MESSAGE);
        return;
    } else if (password.isEmpty()) {
        JOptionPane.showMessageDialog(this,
            "Please enter Password!",
            "Registration Error",
            JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    // EMAIL FORMAT VALIDATION
    if (!email.contains("@") || !email.contains(".")) {
        JOptionPane.showMessageDialog(this,
            "Wrong format Email!\nNeed '@' and '.'",
            "Email Format Error",
            JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    // PASSWORD LENGTH VALIDATION
    if (password.length() < 6) {
        JOptionPane.showMessageDialog(this,
            "Password needs 6 characters or more!",
            "Password Too Short",
            JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    // INSERT TO DATABASE
    config con = new config();
    String checkEmailSql = "SELECT * FROM tbl_user WHERE email = ?";
    
    try {
        java.sql.ResultSet rs = con.getData(checkEmailSql, email);
        
        if (rs != null && rs.next()) {
            // May nahanap = ginamit na ang email
            JOptionPane.showMessageDialog(this,
                "This email is already registered!\n" +
                "Please use a different email address.",
                "Email Already Exists",
                JOptionPane.ERROR_MESSAGE);
            return; // Huwag ituloy ang registration
        }
    } catch (java.sql.SQLException e) {
        JOptionPane.showMessageDialog(this,
            "Error checking email: " + e.getMessage(),
            "Database Error",
            JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    // INSERT TO DATABASE (kung hindi pa ginamit ang email)
    String sql = "INSERT INTO tbl_user (username, email, pass, role, status) VALUES (?, ?, ?, ?, ?)";
    con.addRecord(sql, username, email, password, "user", "Pending");
    
    // SUCCESS MESSAGE
    JOptionPane.showMessageDialog(this,
        "Registration Successful!\n\n" +
        "Your account is pending approval.\n" +
        "Please wait for admin to approve your account.",
        "Success",
        JOptionPane.INFORMATION_MESSAGE);
    
    // CLEAR FIELDS
    name.setText("");
    uemail.setText("");
    pass.setText("");
    
    // GO TO LOGIN
    this.dispose();
    loginform login = new loginform();
    login.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        this.dispose();
      loginform login = new loginform();
      login.setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    private void uemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uemailActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        this.dispose();
        loginform login = new loginform();
        login.setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        loginform login = new loginform();
        login.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registerpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registerpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registerpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registerpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registerpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField name;
    private javax.swing.JPasswordField pass;
    private javax.swing.JTextField uemail;
    // End of variables declaration//GEN-END:variables

    private void createAdminIfNotExists() {
    

}

    
}
